import type { Facility } from './site-config';
export type FaqItem = { id: string; question: string; answer: string; link?: { label: string; href: string } };
export type FaqGroup = { id: string; title: string; items: FaqItem[] };
const contact = { label: 'Prata med oss', href: '#kontakt' };
export function facilityFaq(f: Facility): FaqGroup[] {
  const pending = Boolean(f.openingNotice);
  const membership = { label: pending ? 'Förboka medlemskap – 299 kr/mån' : 'Välj medlemskap', href: pending ? '/skonsmon#forboka' : '/medlemskap' };
  return [
    { id: 'bli-medlem', title: 'Kom igång', items: [
      { id: 'borja', question: `Hur blir jag medlem på IW nära ${f.name}?`, answer: pending ? 'Vad roligt att du vill vara med från starten! Förboka genom att lämna ditt namn och mobilnummer. Vi kontaktar dig inför öppningen i november 2026 med information om medlemskapet och nästa steg.' : 'Börja på vår medlemskapssida, välj det alternativ som passar dig och fortsätt till GymControl för registrering och köp. Vill du hellre ha personlig hjälp? Hör av dig så tar vi det tillsammans.', link: membership },
      { id: 'pris', question: 'Vad kostar ett medlemskap?', answer: pending ? 'Du som förbokar i Skönsmon får priset 299 kr/mån. Gymmet beräknas öppna i november 2026 och kommer därefter att vara öppet dygnet runt. Vi går igenom villkoren med dig innan du tecknar medlemskapet.' : 'I Sörberge kostar vuxenmedlemskap 389 kr/mån. Student, pensionär och ungdom betalar 299 kr/mån. Medlemskapen är obundna med en månads uppsägningstid, och ingen start- eller anslutningsavgift tillkommer. Vi hjälper gärna till att hitta rätt alternativ.', link: membership },
      { id: 'prova', question: pending ? 'Kan jag provträna i Skönsmon redan nu?' : 'Kan jag prova gymmet gratis?', answer: pending ? 'Skönsmon är fortfarande under konstruktion och är inte öppet för besök, visning eller träning. Vi beräknar att öppna i november 2026. Vill du träna redan nu är du varmt välkommen att kontakta oss om ett gratis provpass i Sörberge.' : 'Ja, första passet bjuder vi på för dig som funderar på medlemskap. Välj egen provträning eller en introduktion med hjälp. Vid introduktion kontaktar vi dig och hittar en tid tillsammans, så att du får en lugn och personlig start.', link: { label: 'Provträning i Sörberge', href: '/medlemskap#starta' } },
      { id: 'nyborjare', question: 'Passar gymmet mig som aldrig har tränat på gym?', answer: 'Absolut. Du behöver inte vara gymvan eller veta hur maskinerna fungerar för att känna dig välkommen. Vi utgår från dig och hjälper dig att hitta en trygg start och ett upplägg som passar din vardag. ' + (pending ? 'I Skönsmon blir träning och introduktion möjliga efter öppningen.' : 'Boka gärna en introduktion så får du hjälp från början.'), link: contact },
      { id: 'alder', question: 'Vilken åldersgräns gäller?', answer: 'Åldersgränsen är 18 år och vi vill se legitimation vid registreringen. Är du 15–18 år är du välkommen att kontakta oss. Vi gör då en individuell bedömning av om du kan teckna medlemskap och träna på våra anläggningar.', link: contact },
      ...(pending ? [
        { id: 'oppning', question: 'När öppnar IW Nära Skönsmon?', answer: 'Vi bygger just nu vår nya anläggning på Fridhemsgatan 71 i Sundsvall. Den beräknas tas i bruk i november 2026. Exakt öppningsdag meddelas när den är klar – du som förbokar blir kontaktad inför öppningen.' },
        { id: 'forbokning', question: 'Hur förbokar jag medlemskap i Skönsmon?', answer: 'Klicka på Förboka medlemskap och fyll i ditt namn och mobilnummer. Vi kontaktar dig inför öppningen och berättar hur du går vidare med erbjudandet på 299 kr/mån. Ingen betalning görs i intresseformuläret.', link: membership },
      ] : []),
    ] },
    { id: 'medlemskap-betalning', title: 'Medlemskap & betalning', items: [
      { id: 'bindning', question: 'Har ni bindningstid eller uppsägningstid?', answer: 'Vi erbjuder obundet medlemskap med autogiro och en månads uppsägningstid. Du får alltid läsa villkoren innan du tecknar ditt medlemskap. Är något oklart hjälper vi dig gärna. ' + (pending ? 'För Skönsmons förbokning går vi igenom villkor och startdatum inför öppningen.' : '') },
      { id: 'uppsagning', question: 'Hur säger jag upp mitt medlemskap?', answer: 'Du kan hantera uppsägningen via ditt konto eller kontakta oss för hjälp. För autogiro gäller en månads uppsägningstid. Hör gärna av dig om du är osäker på sista träningsdag eller en betalning, så reder vi ut det tillsammans.', link: contact },
      { id: 'betalning', question: 'Hur betalar jag och finns det någon startavgift?', answer: 'Vi tar emot kort, Swish, faktura och kontant betalning och erbjuder medlemskap med autogiro. Ingen start- eller anslutningsavgift tillkommer. Vilka alternativ som visas beror på vad du köper – kontakta oss gärna om du vill ha hjälp.' },
      { id: 'klippkort', question: 'Finns det engångspass, klippkort eller årskort?', answer: 'För dig som tränar mer sällan erbjuder vi engångspass och 10-klipp. Ett 10-klipp gäller i ett år. Vi fokuserar på dessa alternativ och autogiro med en månads uppsägningstid. Fråga oss om du vill betala för en längre period. ' + (pending ? 'Skönsmon kan användas först när anläggningen har öppnat.' : 'Ett engångspass i Sörberge kostar 99 kr och ger tillgång hela dagen.'), link: contact },
      { id: 'rabatt', question: 'Har ni pris för studenter, pensionärer och ungdomar?', answer: pending ? 'Förbokningspriset i Skönsmon är 299 kr/mån. Kontakta oss gärna om vilken medlemsform som passar dig. Åldersgränsen är normalt 18 år; för 15–18 år gör vi en individuell bedömning.' : 'Ja, i Sörberge är priset 299 kr/mån för student, pensionär och ungdom. Vi vill se legitimation och, för studerande över 18 år, ett intyg som visar att du studerar. Kontakta oss om medlemskap för dig som är 15–18 år.' },
      { id: 'pausa', question: 'Kan jag pausa eller frysa medlemskapet?', answer: 'Ja, vid medicinska åkommor kan medlemskapet pausas. Läkarintyg krävs, men vi tar ingen avgift för pausen. Kontakta oss så hjälper vi dig med hur du går vidare och hanterar intyget.', link: contact },
      { id: 'betalningsproblem', question: 'Vad gör jag om betalningen eller medlemskapet krånglar?', answer: 'Hör av dig till oss, så hjälper vi dig att reda ut vad som har hänt. Berätta gärna vilken betalning eller vilket medlemskap det gäller. Skicka inte kortuppgifter eller känsliga personuppgifter i ett vanligt mejl.', link: contact },
      { id: 'flera-gym', question: 'Gäller medlemskapet på alla era anläggningar?', answer: 'Ja, medlemskapet ger tillgång till våra tre anläggningar: Sörberge, Iron Works i centrum och Skönsmon. Skönsmon är under konstruktion och blir tillgängligt först efter öppningen, som beräknas till november 2026. Vi hjälper dig gärna med frågor om tillträde.' },
    ] },
    { id: 'traning-hjalp', title: 'Träning & personlig hjälp', items: [
      { id: 'maskinhjalp', question: 'Kan någon visa mig maskinerna?', answer: pending ? 'Vi hjälper dig gärna att lära känna utrustningen efter öppningen. Just nu är Skönsmon en byggarbetsplats och vi kan inte erbjuda visning eller introduktion där. Vill du komma igång tidigare kan vi ordna en introduktion i Sörberge.' : 'Gärna! Kontakta oss så hittar vi en tid för att visa gymmet och utrustningen. Då kan du ställa frågor och prova i lugn och ro. En personlig genomgång är ett bra sätt att känna sig trygg från första passet.', link: contact },
      { id: 'utrustning', question: 'Vilken utrustning finns på gymmet?', answer: pending ? 'Vi skapar ett gym med handplockade styrkemaskiner, hantlar och skivstänger för träning av hela kroppen. Mer information om den färdiga utrustningen kommer närmare öppningen. Bilderna visar miljön under uppbyggnad.' : 'I Sörberge finns styrkemaskiner, fria vikter och konditionsutrustning, bland annat löpband och motionscyklar. Vi handplockar utrustning från olika märken för att ge dig bra möjligheter att träna hela kroppen. Undrar du över en viss maskin? Fråga oss gärna.', link: { label: 'Se bilder', href: `/${f.slug}#bilder` } },
      { id: 'pt', question: 'Kan jag få personlig hjälp eller träna med en PT?', answer: 'Vår personal är utbildade personliga tränare med kunskap inom träning och kost. Berätta om dina mål och vilken hjälp du söker, så pratar vi om ett upplägg för dig. Vi går igenom innehåll och eventuellt pris innan du bokar.', link: contact },
      { id: 'program', question: 'Kan jag få ett träningsprogram?', answer: 'Ja, vi hjälper dig att hitta ett träningsschema och ett individuellt program som passar din erfarenhet, dina mål och tiden du har. I Sörberge kan du börja med ett gratis provpass och en genomgång. För Skönsmon planerar vi din start inför öppningen.', link: contact },
      { id: 'kost', question: 'Kan jag få hjälp med kost och träningsupplägg?', answer: 'Ja, vår personal har kunskap inom både träning och kost. Vi lyssnar på vad du vill uppnå och hjälper dig att hitta vanor som fungerar i vardagen. Hör av dig och berätta vad du behöver stöd med så tar vi nästa steg tillsammans.', link: contact },
      { id: 'regler', question: 'Vilka trivselregler gäller på gymmet?', answer: 'Inneskor, sunt förnuft och omtanke om varandra räcker långt. Visa hänsyn, plocka undan efter dig och lämna utrustningen i gott skick. Vi vill att alla ska trivas och känna sig välkomna, oavsett träningsvana.' },
    ] },
    { id: 'tilltrade-regler', title: 'Öppettider & tillträde', items: [
      { id: 'oppettider', question: `När är gymmet i ${f.name} öppet?`, answer: pending ? 'Skönsmon beräknas öppna i november 2026. Därefter kommer gymmet att vara öppet dygnet runt, alla dagar, så att du kan träna när det passar din vardag. Fram till öppningen är anläggningen stängd för besök och träning.' : 'Sörberge är öppet alla dagar klockan 06:00–23:00. Du kommer in med din app och kan välja en tid som passar dig. Vill du ha en personlig introduktion bestämmer vi tid tillsammans i förväg.' },
      { id: 'appen', question: 'Hur kommer jag in – behöver jag app eller tagg?', answer: 'Du använder appen Gym Control, som finns där du hämtar appar. Logga in med din registrerade e-postadress. Första lösenordet är födelsedag och månad med inledande nollor, till exempel 19/04. Behöver du en fysisk tagg går det att ordna efter personlig kontakt. ' + (pending ? 'Inpassering till Skönsmon blir tillgänglig efter öppningen.' : ''), link: contact },
      { id: 'obemannat', question: 'Är gymmet obemannat och kan jag ändå få hjälp?', answer: 'Obemannat betyder att du låser upp med appen och tränar på egen hand. Den personliga kontakten finns ändå nära. Vi finns ett samtal bort när du har frågor om träningen eller behöver hjälp med något som krånglar. En introduktion bokar vi tillsammans i förväg.', link: contact },
      { id: 'accessproblem', question: 'Vad gör jag om appen inte fungerar eller jag tappar min tagg?', answer: 'Kontakta oss personligen så hjälper vi dig med tillträdet. Om du har tappat en tagg berättar du det så snart som möjligt, så kan vi hjälpa dig med spärr och nästa steg. Släpp inte in någon på ditt eget medlemskap.', link: contact },
    ] },
    { id: 'praktiskt', title: 'På gymmet', items: [
      { id: 'adress', question: `Var ligger IW nära ${f.name}?`, answer: `Du hittar oss på ${f.address}. ` + (pending ? 'Anläggningen är under konstruktion. Vänta med ditt besök tills vi har öppnat i november 2026.' : 'Välkommen att kontakta oss om du vill boka en introduktion eller behöver hjälp att hitta.'), link: { label: 'Adress och kontakt', href: '#kontakt' } },
      { id: 'omkladning', question: 'Finns det omklädningsrum, dusch och skåp?', answer: (pending ? 'När Skönsmon öppnar kommer det att finnas omklädningsrum, dusch och skåp, precis som på våra andra anläggningar. ' : 'Ja, det finns omklädningsrum, dusch och skåp på våra anläggningar. ') + 'Ta med eget lås till skåpet. Handdukar finns att låna på IW nära Sörberge och, efter öppningen, Skönsmon. Lägg handduken i tvättkorgen efter användning.' },
      { id: 'parkering', question: 'Finns det parkering nära gymmet?', answer: pending ? 'Ja, vid Skönsmon finns parkering mot en mindre avgift. Se aktuell avgift och villkor i Parkster för Fridhemsgatan 71, Skönsmonhuset, och följ skyltningen på plats när gymmet har öppnat.' : 'Ja, parkeringen vid IW nära Sörberge är gratis. Följ skyltningen på plats och hör av dig om du behöver hjälp att hitta till gymmet.' },
      { id: 'van', question: 'Kan jag ta med en vän som inte är medlem?', answer: 'Vad roligt om du vill introducera en vän! Vännen behöver registrera sig själv och använda ett eget gratis prova-på-pass. I Sörberge kan ni komma igång redan nu. Skönsmon är ännu stängt och kan inte användas för provträning före öppningen.', link: { label: 'Kom igång i Sörberge', href: '/medlemskap#starta' } },
      { id: 'butik', question: 'Har ni en butik på gymmet?', answer: 'Ja, på butikssidan ser du våra sju produkter, priser och korta beskrivningar. Välj en vara som finns på plats och använd produktens Swish-knapp. Kontrollera mottagare, belopp och meddelande i Swish innan du godkänner betalningen. Butiken nås också via QR-kod.', link: { label: 'Till butiken', href: '/butik' } },
    ] },
    { id: 'friskvard-foretag', title: 'Friskvård & kontakt', items: [
      { id: 'friskvard', question: 'Kan jag använda friskvårdsbidrag?', answer: 'Ja, vi tar emot friskvårdsbidrag och är anslutna till de stora friskvårdsportalerna. Ett enkelt sätt är att köpa medlemskapet, spara kvittot och lämna det till din arbetsgivare. Stäm av arbetsgivarens rutiner om du är osäker, så hjälper vi dig med underlaget.' },
      { id: 'foretag', question: 'Erbjuder ni företagskort eller företagsavtal?', answer: 'Ja, vi erbjuder företagsrabatter. Berätta om företaget och vad ni söker, så hittar vi en individuell lösning som gör det enklare för kollegorna att träna. Kontakta oss för att prata om upplägg och villkor.', link: contact },
      { id: 'kontakt', question: 'Hur kontaktar jag er?', answer: 'Mejla info@iwnara.se eller ring Lars på 070-753 92 39, Stefan på 076-779 21 21 eller Kim på 072-317 21 62. Lars och Stefan är ägare och Kim är driftansvarig. Ingen fråga är för liten – vi hjälper dig gärna med medlemskap, träning och öppningen i Skönsmon.', link: contact },
    ] },
  ];
}
